apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-nginx
  template:
    metadata:
      labels:
        app: multitool-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: alpine:latest
        command: ["sleep", "3600"] # если контейнер будет сразу выключаться
