apiVersion: v1
kind: Namespace
metadata:
  name: test-nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Waiting for nginx-service to be available..."
            until nslookup nginx-service.test-nginx.svc.cluster.local; do
              sleep 2
            done
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
